FROM python:3.8.10 
ENV PYTHONUNBUFFERED 1 
WORKDIR /diu 
ADD . /diu 
COPY ./requirements.txt /diu/requirements.txt 
RUN sudo apt-get install python-is-python3
RUN  ython -m 
RUN pip install -r requirements.txt
RUN sudo apt-get install python3-opencv
COPY . /diu
