# Generated by Django 3.2.3 on 2021-08-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_covidtestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidtestdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
