# Generated by Django 3.2.3 on 2021-08-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_covidtestdata_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovidTestData',
            new_name='CovidTestImage',
        ),
        migrations.CreateModel(
            name='CovidResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resnet', models.CharField(max_length=255)),
                ('vgg', models.CharField(max_length=255)),
                ('inception', models.CharField(max_length=255)),
                ('exception', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
