# Generated by Django 3.2.6 on 2021-08-19 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_covidresultdata_covid_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.FloatField()),
                ('saturation_ratio', models.FloatField()),
                ('temperature', models.FloatField()),
                ('oxygen_level', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
