# Generated by Django 3.2.6 on 2021-08-19 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_otherreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherreports',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
