# Generated by Django 3.2.6 on 2021-08-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_otherreports_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_info', models.CharField(max_length=120)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assigndoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OtherReports',
        ),
        migrations.AddField(
            model_name='assigndoctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AddField(
            model_name='assigndoctor',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
