# Generated by Django 3.2.6 on 2021-08-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210829_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
    ]
