# Generated by Django 3.2.6 on 2021-08-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_assigndoctor_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=120)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='conditioninfo',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='assignDoctor',
        ),
        migrations.DeleteModel(
            name='ConditionInfo',
        ),
    ]
